let a;
let b;
let c;
let d;
let e;
let M;
a = Number(prompt("Enter la note a"));
console.log(a);
b = Number(prompt("Enter la note b"));
console.log(b);
c = Number(prompt("Enter la note c"));
console.log(c);
d = Number(prompt("Enter la note d"));
console.log(d);
e = Number(prompt("Enter la note e"));
console.log(e);
M = (a + b + c + d + e) / 5;
console.log("la moyenne est:", M);
